"""Add InstitutionType and EducationInstitution models

Revision ID: 54b73ad019a2
Revises: 7ddae5bd796d
Create Date: 2025-12-10 01:29:52.237908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b73ad019a2'
down_revision = '7ddae5bd796d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_types')),
    sa.UniqueConstraint('type_name', name=op.f('uq_institution_types_type_name'))
    )
    op.create_table('education_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_education_institutions_author_id_users')),
    sa.ForeignKeyConstraint(['type_id'], ['institution_types.id'], name=op.f('fk_education_institutions_type_id_institution_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education_institutions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education_institutions')
    op.drop_table('institution_types')
    # ### end Alembic commands ###
