"""Add about_me and last_seen to User

Revision ID: 7ddae5bd796d
Revises: dcca2c42d3fe
Create Date: 2025-12-02 04:19:27.294974

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '7ddae5bd796d'
down_revision = 'dcca2c42d3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('about_me', sa.String(length=200), nullable=True, server_default='')  # дефолтний опис
        )
        batch_op.add_column(
            sa.Column('last_seen', sa.DateTime(), nullable=False, server_default=sa.text(f"'{datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}'"))
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
